[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
# this line errors
my-crate = { path = "../my-crate/library", package = "my-crate-library" }

# this works
my-crate-library = { path = "../my-crate/library" }
